
"use strict";

var path = require('path'),
  sensitive = require('./sensitive');


module.exports = {
  // Project version.
  version: '#{VERSION}',

  // Port to serve on.
  port: '8080',

  /* Session secret to encrypt cookies. */
  secret: sensitive.sessionSecret,

  /*
    Data backend to use for this application.
  */
  dataBackend: 'datastore',

  /*
    Change this to use a different storage bucket than the default.
  */
  cloudStorageBucket: '#{PROJECT_ID}',

  /*
    ID of the project in the developer's console.
  */
  gcloud: {
    projectId: '#{PROJECT_ID}'
  },

  /*
    The client ID and secret can be obtained by generating a new Client ID for
    a web application on Google Developers Console.
  */
  oauth2: {
    clientId: sensitive.clientId,
    clientSecret: sensitive.clientSecret,
    authUrl: '/oauth2/authorize',
    logoutUrl: '/oauth2/logout',
    redirectUrl: process.env.OAUTH2_CALLBACK || 'http://localhost:8080/oauth2callback',
    scopes: ['email', 'profile']
  },

  /*
    Declare top-level site navigation here - linknames mapped to routes. The menu
    will be auto generated by the template in `views/layout/nav.t`.
  */
  nav: {}
};
